spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
#          ddl-auto: create
    generate-ddl: false
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#    open-in-view: false

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tutorialdb?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: dreamerwalker@gmail.com
    password: t3k9ru4j
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required : true


logging:
  level:
    org.springframework: INFO
  #    org.springframework: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: SLF4J_logging.log