spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tutorialdb?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: 05941987Jeka
